### PR TITLE
add mention of platinum open-access

### PR DESCRIPTION
**Pull request by pdebuyl**
See #93

### CODE REVIEW

**Comment by oliviaguest** [comment]
@rougier is this easy to merge and compile? ☺️

**Comment by pdebuyl** [comment]
Provided you have ruby installed and the required gems, it *should* be as easy as running publish.sh. I have issues though, when I try it mixes the sources and master branches.

**Comment by pdebuyl** [comment]
Regarding this PR, there is no build sorry. It is only the README.md file that is not rendered anywhere.

The PR here https://github.com/ReScience/rescience.github.io/pull/87 needs a build.

**Comment by oliviaguest** [comment]
Ha! Sorry! I'm merging this one then since it's easy.

**Pull request merged**
