### PR TITLE
Made suggested changes proposed in #30

### PR DESCRIPTION
**Pull request by rougier**
Those are the corrections proposed by @labarba relative to consistent usage of reproducible / replicable (replication mostly).

Need to do the same for the website.

### CODE REVIEW

**Comment by rougier** [comment]
@khinsen @labarba Any comment on this PR ?

**Comment by khinsen** [comment]
I have no opinion about this at all. From my point of view, the modified version is neither better nor worse. What ReScience is about is something that doesn't fit existing terminology at all, it's neither reproduction nor replication, no matter which set of definitions one adopts.

Using the terminology of Peng and others, reproduction would require the original paper to be reproducible (in which case there is nothing to publish in ReScience), whereas replication would imply redoing everything, experiments *and* code, and check if the results are "close enough", which is a scientific judgement. ReScience is about something in between where new code gets written but not new experiments are involved, and results are expected to be as identical as technically possible.

**Comment by labarba** [comment]
In my opinion, writing new code from scratch and running it to get the same results of a publication that did not publish code, fits the Peng et al. definition of *replication*. The experiments *are* new: new code, new researcher, new lab, new data being collected. As independent as it gets!

As Donoho says, though: if the new results do not match the publication, it will be impossible to know *why*, because the original publication was not reproducible. Without access to the original code, the source of the differences cannot be found.

**Comment by rougier** [comment]
I propose to not start a new discussion here (but you can continue in other threads of course).
If you're ok, just thumb up and I'll merge.

**Pull request merged**
