### PR TITLE
Almost complete rewrite of the reviewer guidelines

### PR DESCRIPTION
**Pull request by khinsen**

### CODE REVIEW

**Comment by rougier** [comment]
One problem that have been raised some time ago is that we are supposed to accept failed replication and we do not say much about this (but in the FAQ).  We probably need to distinguish between the two situations for the review (failure or success).

**Comment by khinsen** [comment]
Good catch! I added a section on failed replications

**Comment by rougier** [comment]
Quoting `The goal of the review is not to "accept" or "reject"` seems a bit ambiguous since we ask reviewers to either accept or reject the submission. We thus need to modify the submission template and find a new formula for reviewers to signify the submission has reached a good quality.

**Comment by rougier** [comment]
By the way, I just forgot to thank you for the new text which is much better...

**Comment by khinsen** [comment]
I think we should stick to the established vocabulary of accept/reject. I hope my new paragraph is clearer about the intention: Re**Science** is not a journal that takes pride in its high rejection rate (which for now remains zero).

**Pull request merged**
